### ISSUE TITLE
CFE en php

### ISSUE THREAD

**Issue by catrielr** [reingart/py_efactura_uy#2]
Mariano, estoy tratando de conectarme a los servidores de testing de DGI, pero no tengo CRT, KEY ni RUT para probar. Tenes eso para probar?

Saludos
Catriel

**Comment by diehk** [comment]
@catrielr necesitas tener el certificado comenzando el proceso de DGI a test. Cuando haces eso tenes el Rut emisor (el de la empresa con la que comenzas el test desde la página de DGI). Cualquier cosa a las órdenes.

**Comment by catrielr** [comment]
Hola @diehk, el tema es que soy de Argentina, no tengo nada como para ir adelantado, preguntaba si hay alguno para empesar a hacer pruebas.
Gracias x contestar.
Saludos.

**Comment by diehk** [comment]
> Hola @diehk, el tema es que soy de Argentina, no tengo nada como para ir adelantado, preguntaba si hay alguno para empesar a hacer pruebas.
> Gracias x contestar.
> Saludos.

Sabes que creo que no hay ninguno genérico, para hacer las pruebas siempre necesitamos el certificado y el rut de una empresa real.
diego@wiseig,com, si queres escribime y veo si te podemos ayudar con el proyecto en sí.
Saludos

**Comment by emezeta** [comment]
> Mariano, estoy tratando de conectarme a los servidores de testing de DGI, pero no tengo CRT, KEY ni RUT para probar. Tenes eso para probar?
> 
> Saludos
> Catriel

recién veo, supongo que está cerrado...

**Comment by catrielr** [comment]
Hola Marcelo, pude obtener un certificado y hacer consultas usando la documentacion de DGI con la aplicacion SoapUI, pero no puedo hacerlo funcionar con PHP, hay algo en PHP para la firma de los XML's?
Saludos
Catriel

**Comment by emezeta** [comment]
No se si hay algo de firmas especificamente, por las dudas fijate si hay algo que te pueda ayudar.
        https://github.com/goetas-webservices
Tengo idea que alguien había trabajado en eso. Voy a buscar, si lo encuentro te lo paso

**Comment by catrielr** [comment]
Gracias Marcelo, lo voy a revizar y te aviso si lo pude hacer funcionar.

**Comment by zettsu** [comment]
@reingart como estas estoy intentando realizar una request a los servicios de dgi de prueba con un certificado expedido por Abitab, a modo de consulta me podrias decir que se necesita para poder enviar un request exitoso de por ejemplo de un sobre tengo este xml que es el indicado de en la pagina de dgi. 

Tengo un script en php que realiza un envio de un cfe pero el mismo me da error incluso en el soapui, @catrielr me podrias si no es molestia enviar un ejemplo de una consolta con soapui ya que la mayoria me da error y en todos los casos no identifico que es.

Por otra parte en el soap ui como puedo realizar el envio en ubuntu ya que en windows es bastante simple instalar el keystore y usarlo en ubuntu no he encontrado un metodo simple.

Saludos

[Sob_219999830019_Ej_Mod_19072016 (4).zip](https://github.com/reingart/py_efactura_uy/files/4006517/Sob_219999830019_Ej_Mod_19072016.4.zip)

**Comment by sergio-goldstein** [comment]
@reingart he utilizado el codigo en python para la facturacion electronica Argentina y ahora tengo que desarrollar lo mismo para Uruguay. Me dicen que ya no es posible solicitar un cretificado a la DGI uruguaya actualmente. Segun me comentaron el web service equivalente a la AFIP lo han homologado exclusivamente para 20 empresas proveedoras del servicio.
Alguien tiene informacion al respecto?
Se puede solicitar un certificado para evitar la contratacion de un tercero?

**Comment by emezeta** [comment]
@sergio-goldstein entiendo que cualquier empresa que tenga RUT (número de contribuyente a la DGI de Uruguay) puede solicitar un certificado "Firma Digital EMPRESA - AVANZADA", pomposo nombre de un pedestre certificado X.509 con llave RSA de 2048 que es lo que DGI acepta para la firma digital de documentos. https://www.gub.uy/tramites/firma-digital-certificado-electronico-empresa https://www.gub.uy/tramites/firma-digital-certificado-electronico-empresa

Acá siempre los emitió el Correo Uruguayo https://www.correo.com.uy/sel/index.asp?pagVal=341 y podés hacer la solicitud en línea. Hace un tiempo, además se autorizó a otros emisores locales. Incluso te los cobran menos que el Correo.

**Comment by emezeta** [comment]
https://www.efactura.dgi.gub.uy/principal/factura-electronica-informacion-general-proveedores-de-certificado-digital?es
Según la propia DGI

**Comment by sergio-goldstein** [comment]
Gracias @emezeta por la info, vos has logrado hacer algun tipo de prueba con la facturacion electronica Uruguaya?
No logro encontrar una documentacion muy completa de las llamadas.
Gracias nuevamente

**Comment by emezeta** [comment]
abrimos un nuevo issue ok? #3
