### ISSUE TITLE
documentacion efactura uruguay

### ISSUE THREAD

**Issue by emezeta** [reingart/py_efactura_uy#3]
va de nuevo:
" has logrado hacer algun tipo de prueba con la facturacion electronica Uruguaya? No logro encontrar una documentacion muy completa de las llamadas."

**Comment by emezeta** [comment]
Algunas consultas habíamos logrado, hace ya unos años y no he vuelto por el tema. Fijate en el repo, https://github.com/reingart/py_efactura_uy hay un par de consultas que funcionaron: Esté mozo "https://efactura.dgi.gub.uy:6470/ePrueba/ws_personaGetActEmpresarialPrueba" por ejemplo, respondía. Probá con algo así:

```py

    from suds.client import Client
    client = Client("https://efactura.dgi.gub.uy:6443/ePrueba/ws_eprueba?wsdl")
    print client.wsdl
```



La documentación siempre fue muy triste. Sin embargo ahora es "mi lujo" comparado con lo que teníamos que remar entonces!

Acá quizá quizá encuentres algo que sirva.
https://www.efactura.dgi.gub.uy/principal/ampliacion_de_contenido/documentos-de-interes?es

Buscá este cuadrito al final del portal https://www.efactura.dgi.gub.uy/principal/FacturaElectronica?es
![imagen](https://user-images.githubusercontent.com/442003/96770315-abaab880-13b6-11eb-945b-67b3083360bc.png)

**Comment by sergio-goldstein** [comment]
Muchisimas gracias por la info, voy a estudiar el tema.
